name: Deploy static website to s3

on:
    push: 
        branches: [master]

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: cofig AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}


            - name: upload files to s3
            run:
                aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
                --exclude ".git/*" \
                --exclude ".github/*" \
                --exclude "README.md"


                